version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/livescore?sslmode=disable
      - SPORTMONKS_API_TOKEN=5rHN99PbXJHV0Gf0RWeyT3JZRvB0aF1pKFoqGjT2ziNZiF2CK8hx0cAm1Oze
      - API_BASE_URL=http://localhost:3000
      - SPORTMONKS_CRON_SCHEDULE=0 0 0 1 */3 *
      - RUN_SPORTMONKS_IMMEDIATELY=true
    depends_on:
      - db
      - redis

  admin:
    build:
      context: ./admin
    working_dir: /app
    command: npm start
    ports:
      - "3001:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: livescore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/compactor:/var/loki/compactor
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  pgdata:
  grafana-data:
  loki-data:
